server:
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    driver-class-name: "${spring.datasource.driver-class-name}"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER
